# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gaganjot Singh
email: gaganjot.in@gmail.com
current_year: 2018
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
copyright_description: > # this means to ignore newlines until "baseurl:"
  Copyright © Gaganjot Singh 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: GaganTheroyal
github_username:  GaganJotSingh
home_username:  Home

# Build settings
markdown: kramdown

# Site URLs
url_my_reading_list: "/reads/"
url_my_blog: "/blog/"
url_my_mini_posts: "/miniPosts/"
url_resume: "/about/resume/"
url_master_thesis: "/study/masterThesis/"
url_idp: "/study/idp/"
url_si2011: "/study/si2011/"
url_courses_undertaken: "/courses/"
url_courses_bachelors: "/courses/#during_bachelors"
url_courses_masters: "/courses/#during_masters"
url_courses_online: "/courses/#moocs"

# Google services
google_analytics: UA-84529288-1
